<?php

/**
 * @file
 * Contains passivate.module
 */

use Drupal\Core\Entity\EntityInterface;

function passivate_node_insert(\Drupal\Core\Entity\EntityInterface $node) {
  $client = \Drupal::httpClient(['headers' => ['secret-key' => '$2a$10$ioC1xzbucqmfX9Y0SO66H.2rqEyeZc2jpFG/r.eInlKWZxQjSTfPi','collection-id' => '5ceda068bc2a75194e4f7606']);

  try {
    $request = $client->post('https://api.jsonbin.io/b', [
      'json' => [
        'id'=> 'helloworld'
      ]
    ]);
    $response = json_decode($request->getBody());
  }
  catch (RequestException $e) {
    watchdog_exception('passivate', $e->getMessage());
  }

}


/**
 * @} End of "defgroup hooks_example".
 */
