<?php

/**
 * @file
 * Contains passivate.module
 */

use Drupal\Core\Entity\EntityInterface;

function passivate_node_insert(\Drupal\Core\Entity\EntityInterface $node) {
  $client = \Drupal::httpClient();

  try {
    $request = $client->post('http://demo.ckan.org/api/3/action/group_list', [
      'json' => [
        'id'=> 'data-explorer'
      ]
    ]);
    $response = json_decode($request->getBody());
  }
  catch (RequestException $e) {
    watchdog_exception('passivate', $e->getMessage());
  }

}


/**
 * @} End of "defgroup hooks_example".
 */
